version: '2'
services:
    proxy:
      image: proxy
      ports:
          - 80:80
      restart: always
 
    nginx:
        depends_on:
            - proxy
        image: nginx:stable-alpine
        restart: always
 
    node:
        depends_on:
            - proxy
        image: mbektasevi1/tutorijal7:1.0
        ports:
            - 8086
        restart: always
    
    bulletin:
        depends_on:
            - proxy
        image: mbektasevi1/bulletinboard:1.0
        ports:
            - 8083
        restart: always